#################
### AUTOSTART ###
#################
exec-once = ln -sf /run/user/1000/hypr /tmp/hypr
exec-once = waybar
exec-once = hyprpaper
exec-once = hypridle
exec-once = eww daemon
exec-once = ~/.config/eww/window-manager.sh
exec-once = rm -f /tmp/eww_temp_history
exec-once = xembedsniproxy
exec-once = mako
exec-once = /usr/lib/x86_64-linux-gnu/libexec/kdeconnectd
