# Hyprland Configuration
# Learn more: https://wiki.hyprland.org/Configuring/

###################
### MY PROGRAMS ###
###################
$terminal = /home/jobe/.local/bin/alacritty
$fileManager = thunar
$menu = rofi -show drun -theme ~/.config/rofi/config.rasi

###################
### MODULAR CONFIG
###################
# Load modular configuration files
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/autostart.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################
