#####################
### LOOK AND FEEL ###
#####################
# Tokyo Night colors
$bg = rgb(1a1b26)
$fg = rgb(c0caf5)
$red = rgb(f7768e)
$green = rgb(9ece6a)
$yellow = rgb(e0af68)
$blue = rgb(7aa2f7)
$magenta = rgb(bb9af7)
$cyan = rgb(7dcfff)
$white = rgb(c0caf5)
$gray = rgb(414868)

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    col.active_border = $blue
    col.inactive_border = $gray
    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 4

    #    shadow {
    #    enabled = true
    #    range = 4
    #    render_power = 3
    #    color = rgba(1a1b26ee)
    #}

    blur {
        enabled = true
        size = 3
        passes = 1
        vibrancy = 0.1696
    }
}

animations {
    enabled = false
}

dwindle {
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    initial_workspace_tracking = 2
}

xwayland {
    force_zero_scaling = true
}
