################
### MONITORS ###
################
monitor=DP-2,1920x1080@120,1920x0,1
# DP-2: Asus VG248 (144Hz capable)
monitor=DP-3,1920x1080@120,0x0,1
# DP-3: BenQ ZOWIE XL LCD (240Hz capable)

# Workspace to monitor bindings
workspace = 1, monitor:DP-3, default:true
workspace = 2, monitor:DP-3
workspace = 3, monitor:DP-3
workspace = 4, monitor:DP-2, default:true
workspace = 5, monitor:DP-2
workspace = 6, monitor:DP-2
workspace = 7, monitor:DP-2
workspace = 8, monitor:DP-2
workspace = 9, monitor:DP-2
